"""users table

Revision ID: 075af41522d2
Revises: 780739b227a7
Create Date: 2022-11-14 15:07:59.123582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075af41522d2'
down_revision = '780739b227a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('strepen', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groep_name'), 'groep', ['name'], unique=True)
    op.create_index(op.f('ix_groep_strepen'), 'groep', ['strepen'], unique=False)
    op.create_table('leider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=True),
    sa.Column('lastname', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('alias', sa.String(length=45), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('groep_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('strepen', sa.String(length=2), nullable=True),
    sa.Column('rekening', sa.String(length=3), nullable=True),
    sa.Column('afwezigheid', sa.String(length=100), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['groep_id'], ['groep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leider_address'), 'leider', ['address'], unique=False)
    op.create_index(op.f('ix_leider_afwezigheid'), 'leider', ['afwezigheid'], unique=False)
    op.create_index(op.f('ix_leider_alias'), 'leider', ['alias'], unique=False)
    op.create_index(op.f('ix_leider_email'), 'leider', ['email'], unique=True)
    op.create_index(op.f('ix_leider_firstname'), 'leider', ['firstname'], unique=False)
    op.create_index(op.f('ix_leider_lastname'), 'leider', ['lastname'], unique=False)
    op.create_index(op.f('ix_leider_rekening'), 'leider', ['rekening'], unique=False)
    op.create_index(op.f('ix_leider_status'), 'leider', ['status'], unique=False)
    op.create_index(op.f('ix_leider_strepen'), 'leider', ['strepen'], unique=False)
    op.create_table('programma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activiteit', sa.String(length=500), nullable=True),
    sa.Column('datum', sa.String(length=45), nullable=True),
    sa.Column('time_posted', sa.DateTime(), nullable=True),
    sa.Column('groep_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groep_id'], ['groep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programma_activiteit'), 'programma', ['activiteit'], unique=False)
    op.create_index(op.f('ix_programma_datum'), 'programma', ['datum'], unique=True)
    op.create_index(op.f('ix_programma_time_posted'), 'programma', ['time_posted'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_programma_time_posted'), table_name='programma')
    op.drop_index(op.f('ix_programma_datum'), table_name='programma')
    op.drop_index(op.f('ix_programma_activiteit'), table_name='programma')
    op.drop_table('programma')
    op.drop_index(op.f('ix_leider_strepen'), table_name='leider')
    op.drop_index(op.f('ix_leider_status'), table_name='leider')
    op.drop_index(op.f('ix_leider_rekening'), table_name='leider')
    op.drop_index(op.f('ix_leider_lastname'), table_name='leider')
    op.drop_index(op.f('ix_leider_firstname'), table_name='leider')
    op.drop_index(op.f('ix_leider_email'), table_name='leider')
    op.drop_index(op.f('ix_leider_alias'), table_name='leider')
    op.drop_index(op.f('ix_leider_afwezigheid'), table_name='leider')
    op.drop_index(op.f('ix_leider_address'), table_name='leider')
    op.drop_table('leider')
    op.drop_index(op.f('ix_groep_strepen'), table_name='groep')
    op.drop_index(op.f('ix_groep_name'), table_name='groep')
    op.drop_table('groep')
    # ### end Alembic commands ###
